"""Stable, lightweight DNAKit public package namespace."""

from dnakit import download, search
from dnakit._version import __version__
from dnakit.chunking import (
    ChunkingConfig,
    ChunkProgress,
    ChunkProgressCallback,
    ChunkStrategy,
    LengthCurriculum,
    LengthCurriculumStage,
    SequenceChunk,
    iter_fasta_chunks,
    iter_sequence_chunks,
    make_length_curriculum,
)
from dnakit.core import (
    DNA,
    DNAAlphabet,
    DNAFeature,
    DNARecord,
    DNASequence,
    DNASet,
    Gap,
    GapKind,
    Interval,
    MetricResult,
    Topology,
)
from dnakit.io import (
    ReadConfig,
    ReadMode,
    RecordSource,
    WriteConfig,
    WriteResult,
    read,
    read_one,
    read_set,
    write,
)
from dnakit.references import (
    DownloadProgress,
    GenomeAssembly,
    GenomeDownloadResult,
    download_genome,
    resolve_genome_assembly,
)
from dnakit.standardize import (
    DatasetValidationConfig,
    DatasetValidationReport,
    NormalizationConfig,
    NormalizationResult,
    ValidationConfig,
    ValidationReport,
    normalize,
    validate,
    validate_set,
)

__all__ = [
    "DNA",
    "ChunkProgress",
    "ChunkProgressCallback",
    "ChunkStrategy",
    "ChunkingConfig",
    "DNAAlphabet",
    "DNAFeature",
    "DNARecord",
    "DNASequence",
    "DNASet",
    "DatasetValidationConfig",
    "DatasetValidationReport",
    "DownloadProgress",
    "Gap",
    "GapKind",
    "GenomeAssembly",
    "GenomeDownloadResult",
    "Interval",
    "LengthCurriculum",
    "LengthCurriculumStage",
    "MetricResult",
    "NormalizationConfig",
    "NormalizationResult",
    "ReadConfig",
    "ReadMode",
    "RecordSource",
    "SequenceChunk",
    "Topology",
    "ValidationConfig",
    "ValidationReport",
    "WriteConfig",
    "WriteResult",
    "__version__",
    "download",
    "download_genome",
    "iter_fasta_chunks",
    "iter_sequence_chunks",
    "make_length_curriculum",
    "normalize",
    "read",
    "read_one",
    "read_set",
    "resolve_genome_assembly",
    "search",
    "validate",
    "validate_set",
    "write",
]
