"""Bounded native thermodynamics and conditional backend discovery."""

from .backends import (
    Primer3CLIAdapter,
    ThermodynamicsBackend,
    conditional_capabilities,
    probe_primer3,
    validate_primer3_result,
)
from .calculations import (
    duplex_stability,
    extinction_coefficient_260nm,
    melting_temperature,
    molecular_weight,
    nearest_neighbor,
    salt_correction,
    stacking_interactions,
    window_tm,
)
from .config import NearestNeighborConfig, SaltModel, ThermodynamicConditions, TmMethod
from .equilibrium import (
    MeltingCurveProgress,
    binding_equilibrium,
    cosolvent_tm_correction,
    terminal_stability,
    theoretical_melting_curve,
)
from .optics import concentration_from_a260, convert_oligo_quantity, optical_properties
from .parameters import (
    PARAMETER_SETS,
    SANTALUCIA_1998,
    NearestNeighborParameter,
    NearestNeighborParameterSet,
)
from .results import (
    A260ConcentrationResult,
    BindingEquilibriumResult,
    ConditionalCapability,
    CosolventCorrectionResult,
    DuplexStabilityResult,
    ExtinctionCoefficientResult,
    LabelAbsorbanceCorrection,
    MeltingCurvePoint,
    MeltingTemperatureResult,
    MolecularWeightResult,
    NearestNeighborResult,
    OligoQuantityResult,
    OpticalModification,
    OpticalPropertiesResult,
    Primer3ThermodynamicResult,
    SaltCorrectionResult,
    StackingResult,
    StackingStep,
    TerminalStabilityResult,
    TheoreticalMeltingCurveResult,
    WindowTmPoint,
    WindowTmResult,
)

__all__ = [
    "PARAMETER_SETS",
    "SANTALUCIA_1998",
    "A260ConcentrationResult",
    "BindingEquilibriumResult",
    "ConditionalCapability",
    "CosolventCorrectionResult",
    "DuplexStabilityResult",
    "ExtinctionCoefficientResult",
    "LabelAbsorbanceCorrection",
    "MeltingCurvePoint",
    "MeltingCurveProgress",
    "MeltingTemperatureResult",
    "MolecularWeightResult",
    "NearestNeighborConfig",
    "NearestNeighborParameter",
    "NearestNeighborParameterSet",
    "NearestNeighborResult",
    "OligoQuantityResult",
    "OpticalModification",
    "OpticalPropertiesResult",
    "Primer3CLIAdapter",
    "Primer3ThermodynamicResult",
    "SaltCorrectionResult",
    "SaltModel",
    "StackingResult",
    "StackingStep",
    "TerminalStabilityResult",
    "TheoreticalMeltingCurveResult",
    "ThermodynamicConditions",
    "ThermodynamicsBackend",
    "TmMethod",
    "WindowTmPoint",
    "WindowTmResult",
    "binding_equilibrium",
    "concentration_from_a260",
    "conditional_capabilities",
    "convert_oligo_quantity",
    "cosolvent_tm_correction",
    "duplex_stability",
    "extinction_coefficient_260nm",
    "melting_temperature",
    "molecular_weight",
    "nearest_neighbor",
    "optical_properties",
    "probe_primer3",
    "salt_correction",
    "stacking_interactions",
    "terminal_stability",
    "theoretical_melting_curve",
    "validate_primer3_result",
    "window_tm",
]
