"""Deterministic dependency-free encodings and fixed-schema fingerprints."""

from dnakit.fingerprints._shared import (
    FingerprintAmbiguityPolicy,
    FingerprintRepresentation,
    GapEncodingPolicy,
    IntegerAmbiguityPolicy,
    KmerFingerprintMode,
    OneHotAmbiguityPolicy,
    SequenceInput,
)
from dnakit.fingerprints.advanced import (
    AdvancedFingerprintResult,
    FeaturePreprocessor,
    ThermodynamicMissingStrategy,
    ThermodynamicStructureAdapter,
    coding_fingerprint,
    fit_preprocessor,
    gc_spatial_fingerprint,
    hybrid_fingerprint,
    motif_fingerprint,
    multiscale_fingerprint,
    repeat_fingerprint,
    restriction_fingerprint,
    thermodynamic_fingerprint,
)
from dnakit.fingerprints.bit import (
    DEFAULT_HASHED_KMER_BITS,
    DEFAULT_MAX_PANEL_SIZE,
    MAX_BIT_FINGERPRINT_DIMENSION,
    PanelMode,
    hashed_kmer_fingerprint,
    panel_fingerprint,
)
from dnakit.fingerprints.encoding import (
    CANONICAL_BASE_ORDER,
    DEFAULT_MAX_OUTPUT_LENGTH,
    INTEGER_AMBIGUITY_CODE,
    INTEGER_GAP_CODE,
    IUPAC_INTEGER_ORDER,
    integer_encode,
    one_hot_encode,
)
from dnakit.fingerprints.kmer import DEFAULT_MAX_DIMENSION, kmer, kmer_fingerprint
from dnakit.fingerprints.results import (
    BitFingerprintResult,
    BitFingerprintValues,
    FingerprintResult,
    FingerprintValues,
    IntegerEncodingResult,
    KmerFingerprintResult,
    Numeric,
    OneHotEncodingResult,
    RepresentationResult,
    SketchResult,
)
from dnakit.fingerprints.sketch import DEFAULT_MAX_SKETCH_HASHES, fracminhash, minhash

__all__ = [
    "CANONICAL_BASE_ORDER",
    "DEFAULT_HASHED_KMER_BITS",
    "DEFAULT_MAX_DIMENSION",
    "DEFAULT_MAX_OUTPUT_LENGTH",
    "DEFAULT_MAX_PANEL_SIZE",
    "DEFAULT_MAX_SKETCH_HASHES",
    "INTEGER_AMBIGUITY_CODE",
    "INTEGER_GAP_CODE",
    "IUPAC_INTEGER_ORDER",
    "MAX_BIT_FINGERPRINT_DIMENSION",
    "AdvancedFingerprintResult",
    "BitFingerprintResult",
    "BitFingerprintValues",
    "FeaturePreprocessor",
    "FingerprintAmbiguityPolicy",
    "FingerprintRepresentation",
    "FingerprintResult",
    "FingerprintValues",
    "GapEncodingPolicy",
    "IntegerAmbiguityPolicy",
    "IntegerEncodingResult",
    "KmerFingerprintMode",
    "KmerFingerprintResult",
    "Numeric",
    "OneHotAmbiguityPolicy",
    "OneHotEncodingResult",
    "PanelMode",
    "RepresentationResult",
    "SequenceInput",
    "SketchResult",
    "ThermodynamicMissingStrategy",
    "ThermodynamicStructureAdapter",
    "coding_fingerprint",
    "fit_preprocessor",
    "fracminhash",
    "gc_spatial_fingerprint",
    "hashed_kmer_fingerprint",
    "hybrid_fingerprint",
    "integer_encode",
    "kmer",
    "kmer_fingerprint",
    "minhash",
    "motif_fingerprint",
    "multiscale_fingerprint",
    "one_hot_encode",
    "panel_fingerprint",
    "repeat_fingerprint",
    "restriction_fingerprint",
    "thermodynamic_fingerprint",
]
