"""Deterministic native sequence and fingerprint similarity tools."""

from dnakit.similarity.approximate import (
    DEFAULT_MAX_APPROXIMATE_CELLS,
    DEFAULT_MAX_APPROXIMATE_MATCHES,
    DEFAULT_MAX_APPROXIMATE_TARGETS,
    approximate_search,
)
from dnakit.similarity.compare import compare, exact_similarity
from dnakit.similarity.dashing import (
    DEFAULT_MAX_DASHING_CAPTURE_BYTES,
    DEFAULT_MAX_DASHING_INPUT_BYTES,
    DEFAULT_MAX_DASHING_ITEMS,
    DEFAULT_MAX_DASHING_OUTPUT_BYTES,
    DEFAULT_MAX_DASHING_SKETCH_MEMORY_BYTES,
    DashingAdapter,
    DashingInput,
    DashingMode,
)
from dnakit.similarity.distance import (
    DEFAULT_MAX_EDIT_CELLS,
    edit_distance,
    hamming_distance,
    levenshtein_distance,
)
from dnakit.similarity.index import (
    SketchIndex,
    build_sketch_index,
    load_sketch_index,
    nearest_neighbors,
    save_sketch_index,
)
from dnakit.similarity.matrix import (
    DEFAULT_MAX_MATRIX_ITEMS,
    pairwise_matrix,
    similarity_matrix,
)
from dnakit.similarity.results import (
    ApproximateMatch,
    ApproximateSearchResult,
    DashingJaccardMatrixResult,
    DashingNeighborHit,
    DashingNeighborRow,
    DashingTopKResult,
    DistanceResult,
    EditStep,
    Mismatch,
    NearestNeighborHit,
    NearestNeighborResult,
    SearchResult,
    SequenceMatch,
    SimilarityMatrixResult,
    SimilarityResult,
    SketchSimilarityResult,
)
from dnakit.similarity.search import (
    DEFAULT_MAX_SEARCH_MATCHES,
    DEFAULT_MAX_SEARCH_TARGETS,
    exact_search,
    find_subsequence,
    reverse_complement_search,
    subsequence_search,
)
from dnakit.similarity.sketch import SketchMetric, sketch_similarity
from dnakit.similarity.vector import (
    fingerprint_similarity,
    kmer_similarity,
    kmer_vector_similarity,
)

__all__ = [
    "DEFAULT_MAX_APPROXIMATE_CELLS",
    "DEFAULT_MAX_APPROXIMATE_MATCHES",
    "DEFAULT_MAX_APPROXIMATE_TARGETS",
    "DEFAULT_MAX_DASHING_CAPTURE_BYTES",
    "DEFAULT_MAX_DASHING_INPUT_BYTES",
    "DEFAULT_MAX_DASHING_ITEMS",
    "DEFAULT_MAX_DASHING_OUTPUT_BYTES",
    "DEFAULT_MAX_DASHING_SKETCH_MEMORY_BYTES",
    "DEFAULT_MAX_EDIT_CELLS",
    "DEFAULT_MAX_MATRIX_ITEMS",
    "DEFAULT_MAX_SEARCH_MATCHES",
    "DEFAULT_MAX_SEARCH_TARGETS",
    "ApproximateMatch",
    "ApproximateSearchResult",
    "DashingAdapter",
    "DashingInput",
    "DashingJaccardMatrixResult",
    "DashingMode",
    "DashingNeighborHit",
    "DashingNeighborRow",
    "DashingTopKResult",
    "DistanceResult",
    "EditStep",
    "Mismatch",
    "NearestNeighborHit",
    "NearestNeighborResult",
    "SearchResult",
    "SequenceMatch",
    "SimilarityMatrixResult",
    "SimilarityResult",
    "SketchIndex",
    "SketchMetric",
    "SketchSimilarityResult",
    "approximate_search",
    "build_sketch_index",
    "compare",
    "edit_distance",
    "exact_search",
    "exact_similarity",
    "find_subsequence",
    "fingerprint_similarity",
    "hamming_distance",
    "kmer_similarity",
    "kmer_vector_similarity",
    "levenshtein_distance",
    "load_sketch_index",
    "nearest_neighbors",
    "pairwise_matrix",
    "reverse_complement_search",
    "save_sketch_index",
    "similarity_matrix",
    "sketch_similarity",
    "subsequence_search",
]
